[package]
name = "ironbelly-wallet"
version = "0.1.0"
authors = ["Ivan Sorokin <ivan@sorokin.io>"]
description = "Ironbelly - Grin mobile wallet"
publish = false
edition = "2018"

[dependencies]
clap = { version = "2.31", features = ["yaml"] }
rpassword = "2.0.0"
ctrlc = { version = "3.1", features = ["termination"] }
failure = "0.1"
failure_derive = "0.1"
prettytable-rs = "0.7"
log = "0.4"
uuid = "0.7.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_derive = "1"

# For Release
# ^
# Does not exist yet

# For bleeding edge
# grin_wallet_api = { git = "https://github.com/cyclefortytwo/grin-wallet", branch = "ironbelly" }
# grin_wallet_impls = { git = "https://github.com/cyclefortytwo/grin-wallet", branch = "ironbelly" }
# grin_wallet_libwallet = { git = "https://github.com/cyclefortytwo/grin-wallet", branch = "ironbelly" }
# grin_wallet_controller = { git = "https://github.com/cyclefortytwo/grin-wallet", branch = "ironbelly" }
# grin_wallet_config = { git = "https://github.com/cyclefortytwo/grin-wallet", branch = "ironbelly" }
# grin_wallet_util = { git = "https://github.com/cyclefortytwo/grin-wallet", branch = "ironbelly" }


# For local testing
grin_wallet_api = { path = "../../../mimblewimble/grin-wallet/api", version = "1.1.0-beta.2" }
grin_wallet_impls = { path = "../../../mimblewimble/grin-wallet/impls", version = "1.1.0-beta.2" }
grin_wallet_libwallet = { path = "../../../mimblewimble/grin-wallet/libwallet", version = "1.1.0-beta.2" }
grin_wallet_controller = { path = "../../../mimblewimble/grin-wallet/controller", version = "1.1.0-beta.2" }
grin_wallet_config = { path = "../../../mimblewimble/grin-wallet/config", version = "1.1.0-beta.2" }
grin_wallet_util = { path = "../../../mimblewimble/grin-wallet/util", version = "1.1.0-beta.2" }



[build-dependencies]
built = "0.3"
cbindgen = "0.8.3"


[lib]
name = "wallet"
crate-type = ["staticlib"]

[patch.crates-io]
croaring = { path = "./croaring-rs", version = "0.3.9" }
